<a href="https://colab.research.google.com/github/saltyyboii/landslide-risk-assessment/blob/main/Experiment-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv("/content/Global_Landslide_Catalog_Export_rows.csv")

In [3]:
df.head()

,source_name,source_link,event_id,event_date,event_time,event_title,event_description,location_description,location_accuracy,landslide_category,...,country_code,admin_division_name,admin_division_population,gazeteer_closest_point,gazeteer_distance,submitted_date,created_date,last_edited_date,longitude,latitude
0,AGU,https://blogs.agu.org/landslideblog/2008/10/14...,684,08/01/2008 12:00:00 AM,NaN,"Sigou Village, Loufan County, Shanxi Province","occurred early in morning, 11 villagers buried...","Sigou Village, Loufan County, Shanxi Province",unknown,landslide,...,CN,Shaanxi,0.0,Jingyang,41.02145,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,107.4500,32.5625
1,Oregonian,http://www.oregonlive.com/news/index.ssf/2009/...,956,01/02/2009 02:00:00 AM,NaN,"Lake Oswego, Oregon",Hours of heavy rain are to blame for an overni...,"Lake Oswego, Oregon",5km,mudslide,...,US,Oregon,36619.0,Lake Oswego,0.60342,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,-122.6630,45.4200
2,CBS News,https://www.cbsnews.com/news/dozens-missing-af...,973,01/19/2007 12:00:00 AM,NaN,"San Ramon district, 195 miles northeast of the...",(CBS/AP) At least 10 people died and as many a...,"San Ramon district, 195 miles northeast of the...",10km,landslide,...,PE,Junín,14708.0,San Ramón,0.85548,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,-75.3587,-11.1295
3,Reuters,https://in.reuters.com/article/idINIndia-41450...,1067,07/31/2009 12:00:00 AM,NaN,Dailekh district,"One person was killed in Dailekh district, pol...",Dailekh district,unknown,landslide,...,NP,Mid Western,20908.0,Dailekh,0.75395,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,81.7080,28.8378
4,The Freeman,http://www.philstar.com/cebu-news/621414/lands...,2603,10/16/2010 12:00:00 PM,NaN,sitio Bakilid in barangay Lahug,Another landslide in sitio Bakilid in barangay...,sitio Bakilid in barangay Lahug,5km,landslide,...,PH,Central Visayas,798634.0,Cebu City,2.02204,04/01/2014 12:00:00 AM,11/20/2017 03:17:00 PM,02/15/2018 03:51:00 PM,123.8978,10.3336

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 11033
Columns: 31

In [5]:
print("===== DATASET SUMMARY =====")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

===== DATASET SUMMARY =====
Number of rows: 11033
Number of columns: 31

In [6]:
print("\n===== COLUMN NAMES =====")
print(df.columns.tolist())

===== COLUMN NAMES =====
['source_name', 'source_link', 'event_id', 'event_date', 'event_time', 'event_title', 'event_description', 'location_description', 'location_accuracy', 'landslide_category', 'landslide_trigger', 'landslide_size', 'landslide_setting', 'fatality_count', 'injury_count', 'storm_name', 'photo_link', 'notes', 'event_import_source', 'event_import_id', 'country_name', 'country_code', 'admin_division_name', 'admin_division_population', 'gazeteer_closest_point', 'gazeteer_distance', 'submitted_date', 'created_date', 'last_edited_date', 'longitude', 'latitude']

In [7]:
print("\n===== DATASET INFORMATION =====")
df.info()

===== DATASET INFORMATION =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11033 entries, 0 to 11032
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   source_name                11033 non-null  object
 1   source_link                10187 non-null  object
 2   event_id                   11033 non-null  int64
 3   event_date                 11033 non-null  object
 4   event_time                 0 non-null      float64
 5   event_title                11033 non-null  object
 6   event_description          10171 non-null  object
 7   location_description       10931 non-null  object
 8   location_accuracy          11031 non-null  object
 9   landslide_category         11032 non-null  object
 10  landslide_trigger          11010 non-null  object
 11  landslide_size             11024 non-null  object
 12  landslide_setting          10964 non-null  object
 13  fatality_count             9648 non-null   float64
 14  injury_count               5359 non-null   float64
 15  storm_name                 577 non-null    object
 16  photo_link                 1496 non-null   object
 17  notes                      317 non-null    object
 18  event_import_source        9470 non-null   object
 19  event_import_id            9471 non-null   float64
 20  country_name               9471 non-null   object
 21  country_code               9469 non-null   object
 22  admin_division_name        9396 non-null   object
 23  admin_division_population  9471 non-null   float64
 24  gazeteer_closest_point     9470 non-null   object
 25  gazeteer_distance          9471 non-null   float64
 26  submitted_date             11023 non-null  object
 27  created_date               11032 non-null  object
 28  last_edited_date           11033 non-null  object
 29  longitude                  11033 non-null  float64
 30  latitude                   11033 non-null  float64
dtypes: float64(8), int64(1), object(22)
memory usage: 2.6+ MB

In [8]:
print("\n===== STATISTICAL SUMMARY =====")
display(df.describe())

===== STATISTICAL SUMMARY =====

,event_id,event_time,fatality_count,injury_count,event_import_id,admin_division_population,gazeteer_distance,longitude,latitude
count,11033.000000,0.0,9648.000000,5359.000000,9471.000000,9.471000e+03,9471.000000,11033.000000,11033.000000
mean,5598.953141,NaN,3.219424,0.751819,4798.563070,1.577600e+05,11.873689,2.520441,25.881887
std,3249.228647,NaN,59.886178,8.458955,2789.125559,8.297345e+05,15.598228,100.908393,20.415054
min,1.000000,NaN,0.000000,0.000000,-111.167300,0.000000e+00,0.000030,-179.980766,-46.774800
25%,2785.000000,NaN,0.000000,0.000000,2386.500000,1.963000e+03,2.363845,-107.871700,13.917600
50%,5563.000000,NaN,0.000000,0.000000,4773.000000,7.365000e+03,6.254870,19.694600,30.534500
75%,8435.000000,NaN,1.000000,0.000000,7189.500000,3.402100e+04,15.815610,93.948000,40.866259
max,11221.000000,NaN,5000.000000,374.000000,9669.000000,1.269184e+07,215.448880,179.991364,72.627500

In [9]:
print("\n===== MISSING VALUES =====")
display(df.isnull().sum())

===== MISSING VALUES =====

source_name                      0
source_link                    846
event_id                         0
event_date                       0
event_time                   11033
event_title                      0
event_description              862
location_description           102
location_accuracy                2
landslide_category               1
landslide_trigger               23
landslide_size                   9
landslide_setting               69
fatality_count                1385
injury_count                  5674
storm_name                   10456
photo_link                    9537
notes                        10716
event_import_source           1563
event_import_id               1562
country_name                  1562
country_code                  1564
admin_division_name           1637
admin_division_population     1562
gazeteer_closest_point        1563
gazeteer_distance             1562
submitted_date                  10
created_date                     1
last_edited_date                 0
longitude                        0
latitude                         0
dtype: int64

In [10]:
print("\n===== LANDSLIDE CATEGORIES =====")
display(df["landslide_category"].value_counts())

===== LANDSLIDE CATEGORIES =====

landslide_category
landslide              7648
mudslide               2100
rock_fall               671
complex                 232
debris_flow             194
other                    68
unknown                  38
riverbank_collapse       37
snow_avalanche           15
translational_slide       9
lahar                     7
earth_flow                7
creep                     5
topple                    1
Name: count, dtype: int64

In [11]:
print("\n===== LANDSLIDE TRIGGERS =====")
display(df["landslide_trigger"].value_counts())

===== LANDSLIDE TRIGGERS =====

landslide_trigger
downpour                   4680
rain                       2592
unknown                    1691
continuous_rain             748
tropical_cyclone            561
snowfall_snowmelt           135
monsoon                     129
mining                       93
earthquake                   89
construction                 82
flooding                     75
no_apparent_trigger          44
freeze_thaw                  41
other                        26
dam_embankment_collapse      12
leaking_pipe                 10
volcano                       1
vibration                     1
Name: count, dtype: int64